name: Test SDCC Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: safdariali/sdcc-8051:4.6.2

    steps:
      - uses: actions/checkout@v4

      - name: Show SDCC version
        run: sdcc --version

      - name: Show packihx version
        run: packihx

      - name: Show sdobjcopy help
        run: sdobjcopy --help | head -20