set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR mcs51)

set(CMAKE_C_COMPILER /usr/local/bin/sdcc)
set(CMAKE_ASM_COMPILER /usr/local/bin/sdcc)

set(CMAKE_C_COMPILER_TARGET mcs51)

set(CMAKE_C_FLAGS_INIT "-mmcs51")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER_WORKS TRUE)